wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.6.10
    start_time: 1629498872
    t:
      1:
      - 1
      4: 3.6.10
      5: 0.12.0
      8:
      - 2
      - 5
adaptation-steps:
  desc: null
  value: 5
dataset:
  desc: null
  value: omniglot
fast-lr:
  desc: null
  value: 0.08989276830061675
meta-lr:
  desc: null
  value: 0.07237899885181234
num-tasks:
  desc: null
  value: 8
shots:
  desc: null
  value: 5
ways:
  desc: null
  value: 5
