wandb_version: 1

adaptation-steps:
  value: 1
dataset:
  value: omniglot
fast-lr:
  value: 0.009658462745110449
meta-lr:
  value: 0.04284064385105128
num-tasks:
  value: 32
shots:
  value: 5
ways:
  value: 5
