wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.006646871784895063
meta-lr:
  value: 0.00439335876277437
num-tasks:
  value: 32
shots:
  value: 1
ways:
  value: 20
