wandb_version: 1

adaptation-steps:
  value: 1
dataset:
  value: omniglot
fast-lr:
  value: 0.0016234030167889381
meta-lr:
  value: 0.021546913449726146
num-tasks:
  value: 32
shots:
  value: 1
ways:
  value: 20
