wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.040266856229079405
meta-lr:
  value: 0.006819818805854476
num-tasks:
  value: 32
shots:
  value: 5
ways:
  value: 20
