wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.09010345144000632
meta-lr:
  value: 0.049189829081437736
num-tasks:
  value: 32
shots:
  value: 5
ways:
  value: 5
