wandb_version: 1

adaptation-steps:
  value: 1
dataset:
  value: omniglot
fast-lr:
  value: 0.08552765637752179
meta-lr:
  value: 0.0127892255357618
num-tasks:
  value: 32
shots:
  value: 1
ways:
  value: 20
