wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.021079312435333553
meta-lr:
  value: 0.06217753715838891
num-tasks:
  value: 16
shots:
  value: 1
ways:
  value: 20
