wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.05653699878577857
meta-lr:
  value: 0.007883645228449677
num-tasks:
  value: 32
shots:
  value: 1
ways:
  value: 5
