wandb_version: 1

adaptation-steps:
  value: 1
dataset:
  value: omniglot
fast-lr:
  value: 0.08119608753543461
meta-lr:
  value: 0.09996462516729487
num-tasks:
  value: 16
shots:
  value: 5
ways:
  value: 5
