wandb_version: 1

adaptation-steps:
  value: 1
dataset:
  value: omniglot
fast-lr:
  value: 0.06558223115619745
meta-lr:
  value: 0.09549962305962091
num-tasks:
  value: 8
shots:
  value: 1
ways:
  value: 20
