wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.07919308423663039
meta-lr:
  value: 0.09579310475200897
num-tasks:
  value: 16
shots:
  value: 1
ways:
  value: 20
