wandb_version: 1

adaptation-steps:
  value: 1
dataset:
  value: omniglot
fast-lr:
  value: 0.029917106414802722
meta-lr:
  value: 0.09357682401018666
num-tasks:
  value: 16
shots:
  value: 1
ways:
  value: 20
