wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.08230363380956845
meta-lr:
  value: 0.019740354815176726
num-tasks:
  value: 16
shots:
  value: 1
ways:
  value: 20
