wandb_version: 1

adaptation-steps:
  value: 1
dataset:
  value: omniglot
fast-lr:
  value: 0.024484078209674836
meta-lr:
  value: 0.07556152794028065
num-tasks:
  value: 32
shots:
  value: 5
ways:
  value: 20
