wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.08493310150229005
meta-lr:
  value: 0.04927500144908289
num-tasks:
  value: 32
shots:
  value: 5
ways:
  value: 5
