wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.06883681090805206
meta-lr:
  value: 0.048820310699024184
num-tasks:
  value: 32
shots:
  value: 5
ways:
  value: 5
