wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.002742400512630208
meta-lr:
  value: 0.052159615872007604
num-tasks:
  value: 32
shots:
  value: 1
ways:
  value: 20
