wandb_version: 1

adaptation-steps:
  value: 1
dataset:
  value: omniglot
fast-lr:
  value: 0.05507748467499739
meta-lr:
  value: 0.015473619718441804
num-tasks:
  value: 16
shots:
  value: 1
ways:
  value: 20
