wandb_version: 1

adaptation-steps:
  value: 1
dataset:
  value: omniglot
fast-lr:
  value: 0.040436488825297184
meta-lr:
  value: 0.0761735620329529
num-tasks:
  value: 16
shots:
  value: 5
ways:
  value: 5
