wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.07119943742865285
meta-lr:
  value: 0.00010414498820378398
num-tasks:
  value: 16
shots:
  value: 5
ways:
  value:
  - 5
  - 20
