wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.054225044508179596
meta-lr:
  value: 0.02464125959792576
num-tasks:
  value: 32
shots:
  value: 5
ways:
  value: 20
