wandb_version: 1

adaptation-steps:
  value: 1
dataset:
  value: omniglot
fast-lr:
  value: 0.021616718717765333
meta-lr:
  value: 0.09044349969677298
num-tasks:
  value: 8
shots:
  value: 5
ways:
  value: 5
