wandb_version: 1

adaptation-steps:
  value: 5
dataset:
  value: omniglot
fast-lr:
  value: 0.05745597456712965
meta-lr:
  value: 0.08484860568766885
num-tasks:
  value: 32
shots:
  value: 5
ways:
  value: 20
