wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.6.10
    start_time: 1629500335
    t:
      1:
      - 1
      4: 3.6.10
      5: 0.12.0
      8:
      - 2
      - 5
adaptation-steps:
  desc: null
  value: 1
adaptation_steps:
  desc: null
  value: 1
channels:
  desc: null
  value: 1
cuda:
  desc: null
  value: 1
data:
  desc: null
  value: ~/data
dataset:
  desc: null
  value: omniglot
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 60000
fast-lr:
  desc: null
  value: 0.06558223115619745
fast_lr:
  desc: null
  value: 0.06558223115619745
fine_tune:
  desc: null
  value: 0
input:
  desc: null
  value: 28
meta-lr:
  desc: null
  value: 0.09549962305962091
meta_learn:
  desc: null
  value: 1
meta_lr:
  desc: null
  value: 0.09549962305962091
num-tasks:
  desc: null
  value: 8
num_tasks:
  desc: null
  value: 8
seed:
  desc: null
  value: 101
shots:
  desc: null
  value: 1
total_num_tasks:
  desc: null
  value: 20000
username:
  desc: null
  value: hikmatkhan-
wand_project:
  desc: null
  value: JStart
wandb_log:
  desc: null
  value: 1
ways:
  desc: null
  value: 20
workers:
  desc: null
  value: 4
