wandb_version: 1

adaptation-steps:
  value: 1
channels:
  value: 1
data:
  value: ~/data
dataset:
  value: omniglot
device:
  value: cuda
epochs:
  value: 5000
fast-lr:
  value: 0.09723096154882492
fine-tune:
  value: 1
input:
  value: 28
meta-learn:
  value: 1
meta-lr:
  value: 0.04117870076169895
num-tasks:
  value: 8
shots:
  value: 5
total-num-tasks:
  value: 20000
username:
  value: hikmatkhan-
wand-project:
  value: Learn2Learn-Omniglot
wandb-log:
  value: 1
ways:
  value: 5
workers:
  value: 4
