wandb_version: 1

adaptation-steps:
  value: 1
channels:
  value: 1
data:
  value: ./data
dataset:
  value: omniglot
device:
  value: cuda
fast-lr:
  value: 0.062400610547005
fine-tune:
  value: 1
input:
  value: 28
meta-learn:
  value: 1
meta-lr:
  value: 0.043645973369238644
model-name:
  value: vanilla
num-epochs:
  value: 5000
num-tasks:
  value: 32
num-workers:
  value: 4
shots:
  value: 5
total-num-tasks:
  value: -1
username:
  value: hikmatkhan-
wand-project:
  value: Sweeper
wandb-log:
  value: 1
ways:
  value: 5
